# Generated by Django 3.0.3 on 2020-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='cost',
        ),
        migrations.AddField(
            model_name='link',
            name='distance',
            field=models.FloatField(default=1, verbose_name='Distance'),
            preserve_default=False,
        ),
    ]
