# Generated by Django 3.0.3 on 2020-03-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_network', '0003_auto_20200302_1014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('tail', 'head'), name='no_dual_links'),
        ),
    ]
